import MediaContent from '../models/media-content';

const mockData: MediaContent[] = [
  new MediaContent({
    id: 3910945,
    title: 'Cowboy Bebop',
    type: 'tv-show',
    genre: 'western',
    releaseYear: 2001,
    rating: 8,
  }),
  new MediaContent({
    id: 5887462,
    title: 'One Punch Man',
    type: 'tv-show',
    genre: 'comedy',
    releaseYear: 2015,
    rating: 9,
  }),
  new MediaContent({
    id: 1104958,
    title: 'Chrono Trigger',
    type: 'game',
    genre: 'rpg',
    releaseYear: 1995,
    rating: 10,
  }),
  new MediaContent({
    id: 5996873,
    title: "Howl's Moving Castle",
    type: 'movie',
    genre: 'drama',
    releaseYear: 2004,
    rating: 10,
  }),
  new MediaContent({
    id: 5586677,
    title: 'Silmarillion',
    type: 'book',
    genre: 'fantasy',
    releaseYear: 1977,
    rating: 9,
  }),
  new MediaContent({
    id: 5985721,
    title: 'Spirited Away',
    type: 'movie',
    genre: 'drama',
    releaseYear: 2001,
    rating: 7,
  }),
  new MediaContent({
    id: 5476820,
    title: 'Dragon Ball Z',
    type: 'tv-show',
    genre: 'action',
    releaseYear: 1989,
    rating: 2,
  }),
  new MediaContent({
    id: 9455763,
    title: 'A Game of Thrones',
    type: 'book',
    genre: 'fantasy',
    releaseYear: 1995,
    rating: 7,
  }),
  new MediaContent({
    id: 4857245,
    title: 'Infinity War',
    type: 'comic',
    genre: 'fantasy',
    releaseYear: 1992,
    rating: 6,
  }),
  new MediaContent({
    id: 1012976,
    title: 'Overwatch',
    type: 'game',
    genre: 'team',
    releaseYear: 2016,
    rating: 7,
  }),
];

export default mockData;
