import { MediaContentItem } from '../types';

const mockData: MediaContentItem[] = [
  {
    id: 1,
    title: 'Cowboy Bebop',
    type: 'tv-show',
    genre: 'western',
    releaseYear: 2001,
    rating: 8,
  },
  {
    id: 2,
    title: 'One Punch Man',
    type: 'tv-show',
    genre: 'comedy',
    releaseYear: 2015,
    rating: 9,
  },
  {
    id: 3,
    title: 'Chrono Trigger',
    type: 'game',
    genre: 'rpg',
    releaseYear: 1995,
    rating: 10,
  },
  {
    id: 4,
    title: "Howl's Moving Castle",
    type: 'movie',
    genre: 'drama',
    releaseYear: 2004,
    rating: 10,
  },
  {
    id: 5,
    title: 'Silmarillion',
    type: 'book',
    genre: 'fantasy',
    releaseYear: 1977,
    rating: 9,
  },
  {
    id: 6,
    title: 'Spirited Away',
    type: 'movie',
    genre: 'drama',
    releaseYear: 2001,
    rating: 7,
  },
  {
    id: 7,
    title: 'Dragon Ball Z',
    type: 'tv-show',
    genre: 'action',
    releaseYear: 1989,
    rating: 2,
  },
  {
    id: 8,
    title: 'A Game of Thrones',
    type: 'book',
    genre: 'fantasy',
    releaseYear: 1995,
    rating: 7,
  },
  {
    id: 9,
    title: 'Infinity War',
    type: 'comic',
    genre: 'fantasy',
    releaseYear: 1992,
    rating: 6,
  },
  {
    id: 10,
    title: 'Overwatch',
    type: 'game',
    genre: 'team',
    releaseYear: 2016,
    rating: 7,
  },
];

export default mockData;
